name: kursol
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  get_it: ^8.0.3
  pdf: ^3.11.3
  percent_indicator: ^4.2.4
  video_player: ^2.9.2
  go_router: ^14.8.0
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.0.17
  permission_handler: ^11.3.1
  flutter_pdfview: ^1.4.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  animated_snack_bar: ^0.4.0

  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  flutter_spinkit: ^5.2.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  google_sign_in: ^6.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.9.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter_gen:
  output: lib/config/gen



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/courses/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf

  #    - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700